//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab11
{
    using System;
    using System.Collections.Generic;
    
    public partial class master
    {
        public int id_master { get; set; }
        public string surname { get; set; }
        public string name { get; set; }
        public string education { get; set; }
        public string qualification { get; set; }
        public Nullable<int> work_expirience { get; set; }
        public byte[] photo { get; set; }
        public Nullable<int> id_procedure { get; set; }
    
        public virtual procedure procedure { get; set; }
    }
}
